spring:
  profiles: peer3
  application:
    name: spring-cloud-eureka
server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003.com
    instance-id: springcloud-eurekaserver-7003
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #eureka集群的时候使用
management:
  endpoints:
    web:
      exposure:
        include: "*"