spring:
  profiles: peer2
  application:
    name: spring-cloud-eureka
server:
  port: 9000
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:9000/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"