server:
  port: 8098
spring:
  profiles:
    active: peer1
  application:
    name: index-show-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/ # 需要改动
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"