server:
  port: 8080
spring:
  profiles:
    active: pro
  application:
    name: person-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:9000/eureka/ # 需要改动
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"